### ISSUE TITLE
Make Site Easier to Use

### ISSUE THREAD

**Issue by bduff9** [bduff9/nfl-meteor#48]
Some ideas (please add to it as you think of them):
- [x] Add modals for confirm save/submit picks ( #59 )
- [x] Indicate that survivor pick has been saved ( #60 )
- [x] Page help?  Tour? ( #61 )
- [x] Better messages/notifications throughout site ( #62 )
- [x] Message/text on picks submitted or on needing to submit? ( #62 )
- [x] Countdown to game 1 of current week somewhere? ( #63 )

What else?

**Comment by bduff9** [comment]
Leaving this issue open for any future thoughts, however the checked ones have been moved into their own ticket

**Comment by bduff9** [comment]
Closing this for 2017, if we think of anymore we can re-open or just make a new ticket
